movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path('choice/', views.choice, name="choice"),
    
    path('index/<int:mode>/', views.index, name="index"),
    
    path('detail/<int:movie_pk>/', views.detail, name="detail"),
    path('movie_comment/<int:movie_pk>/', views.movie_comment, name="movie_comment"),
    path('movie_comment_delete/<int:comment_pk>/<int:movie_pk>/', views.movie_comment_delete, name="movie_comment_delete"),
    
    path('review_create/<int:movie_pk>/', views.review_create, name="review_create"),
    path('review/<int:review_pk>/', views.review, name="review"),
    path('review_update/<int:review_pk>/', views.review_update, name="review_update"),
    path('review_delete/<int:movie_pk>/<int:review_pk>/', views.review_delete, name="review_delete"),
    path('review_comment/<int:review_pk>/', views.review_comment, name="review_comment"),
    path('review_comment_delete/<int:review_pk>/<int:review_comment_pk>/', views.review_comment_delete, name="review_comment_delete"),
    
    path('usercolor_create/', views.usercolor_create, name="usercolor_create"),
    path('usercolor_update/<rgb>/', views.usercolor_update, name="usercolor_update"),
    
    path('voice_process/', views.voice_process, name="voice_process"),    
    
    path('quiz_create/', views.quiz_create, name="quiz_create"),
    path('quiz/', views.quiz, name="quiz"),
    path('quiz_check/', views.quiz_check, name="quiz_check"),
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.choice),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields import CharField, related

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    overview = models.TextField()
    poster_url = models.TextField(null=True)
    naver_grade = models.FloatField(null=True)
    user_grade = models.IntegerField(null=True)
    release_date = models.TextField()
    trailer_url = models.TextField(null=True)

    def __str__(self):
        return self.title

class Color(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    color = models.CharField(max_length=50, null=True) # Main Color
    color_url = models.TextField(null=True) # Frame 
    color_1_R = models.CharField(max_length=50)
    color_1_G = models.CharField(max_length=50)
    color_1_B = models.CharField(max_length=50)
    color_2_R = models.CharField(max_length=50)
    color_2_G = models.CharField(max_length=50)
    color_2_B = models.CharField(max_length=50)
    color_3_R = models.CharField(max_length=50)
    color_3_G = models.CharField(max_length=50)
    color_3_B = models.CharField(max_length=50)
    color_4_R = models.CharField(max_length=50)
    color_4_G = models.CharField(max_length=50)
    color_4_B = models.CharField(max_length=50)
    color_5_R = models.CharField(max_length=50)
    color_5_G = models.CharField(max_length=50)
    color_5_B = models.CharField(max_length=50)
    
    def __str__(self):
        return self.movie.title
    
class MovieComment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    grade = models.IntegerField()
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="reviews")
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    draw = models.ImageField(blank=True, upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ReviewComment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
class UserColorRecord(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    color = models.CharField(max_length=50)
    
class Quiz(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=13)
    draw = models.ImageField(blank=True, upload_to='images/')
    correct_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="corrected_quizs")

movies/forms.py
from django.db.models.base import Model
from django.forms import ModelForm
from .models import MovieComment, Review, ReviewComment, Quiz

class MovieCommentForm(ModelForm):
    class Meta:
        model = MovieComment
        fields = ('grade', 'content')
        
class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('title','content','draw')
        
class ReviewCommentForm(ModelForm):
    class Meta:
        model = ReviewComment
        fields = ('content',)
        
class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ('movie', 'draw')

movies/views.py
from django.shortcuts import render,redirect
from .models import Movie, MovieComment, Review, ReviewComment, UserColorRecord, Quiz
from .forms import ReviewCommentForm, ReviewForm, MovieCommentForm, QuizForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods, require_safe
import math
from django.http import JsonResponse
from django.db.models import Count
import json
import random

@login_required
@require_safe
def choice(request):
    return render(request, 'movies/choice.html')

@login_required
@require_safe
def index(request, mode):                                          # mode : Sorted by 2 - TMDB_Grade / 3 - Release Date / 4 - Search Data / 1, 4~ - Coloring
    if not request.user.usercolorrecord_set.all():
        return redirect('movies:choice')
    
    movies = Movie.objects.all()
    
    # Profile Color Create
    colors = request.user.usercolorrecord_set.all()                # Color List
    last_color = colors[len(colors)-1]                             # Picked Color
    colors = reversed(colors)                                      # Color Sort(Recently)
    
    # Exclude Already Watched Movies
    # temp_movies = Movie.objects.all()
    # movies = []
    # for movie in temp_movies:
    #     for comment in movie.comments.all():                       # Exist request.user Comment
    #         if request.user == comment.user:
    #             break
    #     else:
    #         for review in movie.reviews.all():                     # Exist request.user Review
    #             if request.user == review.user:
    #                 break
    #         else:
    #             movies.append(movie)
    
    # res_movies = []
    
    # Exclude Already Watched Movies(Query Optimization)
    already_watched_movies = set()

    users_moviecomments = MovieComment.objects.filter(user=request.user.pk).values('movie')
    for users_moviecomment in users_moviecomments:
        already_watched_movies.add(users_moviecomment['movie'])

    users_reviews = Review.objects.filter(user=request.user.pk).values('movie')
    for users_review in users_reviews:
        already_watched_movies.add(users_review['movie'])

    # Query Optimization - movie.color_set + Exclude Already Watched Movies + movie.comments_set + movie.comments.all.count()
    movies = Movie.objects.prefetch_related('color_set','comments')\
            .annotate(comment_count=Count('comments'))\
            .exclude(id__in=already_watched_movies)
    
    res_movies = []
    
    # Order by TMDB_Grade + User_Grade
    if mode == 2:
        for movie in movies:
            naver_score = movie.naver_grade
            user_score = 0 
            for comment in movie.comments.all():
                user_score += comment.grade
            if user_score:
                user_score = round((user_score / movie.comment_count),1) * 2
                score = (naver_score + user_score) / 2
            else:
                score = naver_score
            res_movies.append([movie, score])
    
    # Order by Release Date
    elif mode == 3:
        for movie in movies:
            score = movie.release_date
            res_movies.append([movie, score])
    
    # Order by Search
    elif mode == 4:
        datas = request.GET['searchData'].split()                      # Input Data list
        for movie in movies:                                           # query in title : +10, query in overview +1
            temp_cnt = 0
            title = movie.title
            overview = movie.overview
            for data in datas:
                if data in title:
                    temp_cnt += 10
                if data in overview:
                    temp_cnt += 1
            if temp_cnt >= 1:                                          # If query in title, content, Can be Searched
                res_movies.append([movie,temp_cnt])

    # Order by Coloring
    else:
        last_color_rgb = last_color.color[4:-1].split(", ")            # Users R, G, B list

        for movie in movies:
            movie_color = movie.color_set.all()[0]
            score = math.sqrt(
                    math.pow(int(last_color_rgb[0]) - int(movie_color.color_1_R), 2) +\
                    math.pow(int(last_color_rgb[1]) - int(movie_color.color_1_G), 2) +\
                    math.pow(int(last_color_rgb[2]) - int(movie_color.color_1_B), 2)
                ) + \
            math.sqrt(
                    math.pow(int(last_color_rgb[0]) - int(movie_color.color_2_R), 2) +\
                    math.pow(int(last_color_rgb[1]) - int(movie_color.color_2_G), 2) +\
                    math.pow(int(last_color_rgb[2]) - int(movie_color.color_2_B), 2)
                ) + \
            math.sqrt(
                    math.pow(int(last_color_rgb[0]) - int(movie_color.color_3_R), 2) +\
                    math.pow(int(last_color_rgb[1]) - int(movie_color.color_3_G), 2) +\
                    math.pow(int(last_color_rgb[2]) - int(movie_color.color_3_B), 2)
            ) + \
            math.sqrt(
                    math.pow(int(last_color_rgb[0]) - int(movie_color.color_4_R), 2) +\
                    math.pow(int(last_color_rgb[1]) - int(movie_color.color_4_G), 2) +\
                    math.pow(int(last_color_rgb[2]) - int(movie_color.color_4_B), 2)
                ) + \
            math.sqrt(
                    math.pow(int(last_color_rgb[0]) - int(movie_color.color_5_R), 2) +\
                    math.pow(int(last_color_rgb[1]) - int(movie_color.color_5_G), 2) +\
                    math.pow(int(last_color_rgb[2]) - int(movie_color.color_5_B), 2)
                )
            res_movies.append([movie, int(score)])
    
    if mode == 2 or mode == 3 or mode == 4:
        res_movies.sort(key= lambda x: x[1], reverse=True)
    else:
        res_movies.sort(key= lambda x: x[1])
    
    context = {
        'movies': res_movies,
        'last_color': last_color,
        'colors': colors,
        'mode': mode,
    }
    return render(request, 'movies/index.html', context)

@login_required
@require_safe
def detail(request, movie_pk):
    if not request.user.usercolorrecord_set.all():
        return redirect('movies:choice')
    
    movie = Movie.objects.get(id = movie_pk)
    
    # Profile Color Create
    colors = request.user.usercolorrecord_set.all()                # Color List
    last_color = colors[len(colors)-1]                             # Picked Color
    colors = reversed(colors)                                      # Color Sort(Recently)
    
    # User Grade
    comments = movie.comments.all()
    
    user_grade = 0
    if comments:
        for comment in comments:
            user_grade += comment.grade
        user_grade = 2*round(user_grade / len(comments),1)
    else:
        user_grade = "-"
    
    # Comments
    comments = MovieComment.objects.select_related('user').filter(movie = movie)
    # Review Optimization
    reviews = Review.objects.select_related('user').filter(movie = movie)
    
    context = {
        'movie': movie,
        'colors': colors,
        'last_color': last_color,
        'user_grade': user_grade,
        'reviews': reviews,
        'comments': comments,
    }
    return render(request,'movies/detail.html', context)

@login_required
@require_POST
def movie_comment(request, movie_pk):
    movie = Movie.objects.get(pk = movie_pk)
    form = MovieCommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.movie = movie
        comment.user = request.user
        comment.save()
        request.user.point += 10
        request.user.save()
        return redirect('movies:detail', movie_pk)
    return redirect('movies:detail', movie_pk)


@login_required
@require_http_methods(['GET','POST'])
def review_create(request, movie_pk):
    movie = Movie.objects.get(pk = movie_pk)
    
    # Profile Color Create
    colors = request.user.usercolorrecord_set.all()                # Color List
    last_color = colors[len(colors)-1]                             # Picked Color
    colors = reversed(colors)                                      # Color Sort(Recently)
    
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user
            review.save()
            request.user.point += 30
            request.user.save()
            return redirect('movies:detail', movie_pk)
    else:
        form = ReviewForm()
    context = {
        'movie': movie,
        'form': form,
        'last_color': last_color,
        'colors': colors,
    }
    return render(request, 'movies/review_create.html', context)

@login_required
@require_safe
def review(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    
    # Profile Color Create
    colors = request.user.usercolorrecord_set.all()                # Color List
    last_color = colors[len(colors)-1]                             # Picked Color
    colors = reversed(colors)                                      # Color Sort(Recently)
    
    context = {
        'review': review,
        'last_color': last_color,
        'colors': colors,
    }
    return render(request,'movies/review.html', context)
    

@require_POST
def review_comment(request, review_pk):
    if not request.user.is_authenticated:
        return redirect('movies:review', review_pk)
    
    review = Review.objects.get(pk = review_pk)
    if request.method == "POST":
        form = ReviewCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
            request.user.point += 5
            request.user.save()
            return redirect('movies:review', review_pk)
            

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load static %}

{% block option_import %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'movies/css/detail.css' %}">
{% endblock option_import %}

{% block back_URL %} "{% url 'movies:index' 1 %}" {% endblock back_URL %}

{% block content %} 
<div class="main-container">
  <div class="main-header">
  </div>
  <div class="content-wrapper">
    {% comment %} Movie Information {% endcomment %}
    <div class="content-section mt-3">
      <div class="app-card">
        <span>
          <div class="row">
            {% comment %} Title {% endcomment %}
            <div class="col-3">
              <div class="d-flex justify-content-center align-items-center h-100 w-100 " style="position:relative;" data-toggle="modal" data-target="#trailerModal">
              <img src="{{ movie.poster_url }} " alt="" class="h-100" style="border-radius: 10%; position:absolute;">
              <i class="far fa-play-circle" style="font-size:120px; z-index:100;"></i>
              </div>
            </div>
        </span>
        {% comment %} Contents {% endcomment %}
        {% for color in movie.color_set.all %}
        <div class="col-9">
          <div class="row">
            <div class="col-7">
              <h1> {{ movie.title }} </h1>
            </div>
            <div class="col-5 d-flex justify-content-between align-items-center">
              <i class="fas fa-square" style="color: rgb({{color.color_1_R}},{{color.color_1_G}},{{color.color_1_B}}); font-size: 70px; opacity: 0.9;"></i>
              <i class="fas fa-square" style="color: rgb({{color.color_2_R}},{{color.color_2_G}},{{color.color_2_B}}); font-size: 70px; opacity: 0.9;"></i>
              <i class="fas fa-square" style="color: rgb({{color.color_3_R}},{{color.color_3_G}},{{color.color_3_B}}); font-size: 70px; opacity: 0.9;"></i>
              <i class="fas fa-square" style="color: rgb({{color.color_4_R}},{{color.color_4_G}},{{color.color_4_B}}); font-size: 70px; opacity: 0.9;"></i>
              <i class="fas fa-square" style="color: rgb({{color.color_5_R}},{{color.color_5_G}},{{color.color_5_B}}); font-size: 70px; opacity: 0.9;"></i>
            </div>
          </div>
          <div class="app-card__subtext">
            {{ movie.overview }}
          </div>
          <div style="font-size: 17px; font-weight: 400; line-height: 1.6em; border-bottom: 1px solid var(--border-color); padding: 10px;">
            <h5>평균 평점 : {{ movie.naver_grade }} 점 / 유저 평점 : {{ user_grade }} 점</h5>
          </div>
          <div style="font-size: 17px; font-weight: 400; line-height: 1.6em; border-bottom: 1px solid var(--border-color); padding: 10px;">
            <h5>개봉일 : {{ movie.release_date }}</h5>
          </div>
          <div class="d-flex justify-content-center align-items-center" style="height:100px;" data-toggle="modal" data-target="#imageModal">
            {% comment %} Image from Static {% endcomment %}
            {% with movie.pk|stringformat:"i" as moviepk %}
            {% with 'movies/images/'|add:moviepk|add:'.png' as image_static %}
            <img src="{% static image_static %}" alt="" class="h-75 w-100" id="color_url">
            {% endwith %}
            {% endwith %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    {% comment %} Movie Comment {% endcomment %}
    <div class="content-section mt-3">
      <div class="app-card">
        <h2> 한줄평 </h2>
        <hr>
        {% comment %} Comment Create {% endcomment %}
        <div>
          <form action="{% url 'movies:movie_comment' movie.pk %}" method="POST" name="myform" id="myform"
            class="d-flex">
            {% csrf_token %}

            {% comment %} Stars {% endcomment %}
            <div id="full-stars-example-two">
              <div class="rating-group">
                <label aria-label="1 star" class="rating__label" for="grade-1"><i
                    class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="grade" id="grade-1" value="1" type="radio">
                <label aria-label="2 stars" class="rating__label" for="grade-2"><i
                    class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="grade" id="grade-2" value="2" type="radio">
                <label aria-label="3 stars" class="rating__label" for="grade-3"><i
                    class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="grade" id="grade-3" value="3" type="radio">
                <label aria-label="4 stars" class="rating__label" for="grade-4"><i
                    class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="grade" id="grade-4" value="4" type="radio">
                <label aria-label="5 stars" class="rating__label" for="grade-5"><i
                    class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="grade" id="grade-5" value="5" type="radio" checked>
              </div>
            </div>
            {% comment %} Comment Input {% endcomment %}
            <hr>
            <hr>
            <input type="text" name="content" style="background: none; margin-left: 20px; width: 400px; color:white;">
            <button class="btn btn-warning" style="font-weight: 500px; font-size: 20px; margin-left: 5px; width:100px;">등록</button>
            <hr>
            <hr>
          </form>
        </div>
        <div class="app-card__subtext">
          {% comment %} Comment View {% endcomment %}
          {% for comment in comments %}
          <div id="div{{ comment.id }}" onload="loadFunc()">
            {% comment %} StarsNum {% endcomment %}
            {% if comment.grade == 1 %}
            <p><i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; padding: 0 0.1em; font-size: 2rem;"></i></p>
            {% elif comment.grade == 2%}
            <p><i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
            </p>
            {% elif comment.grade == 3%}
            <p>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
            </p>
            {% elif comment.grade == 4%}
            <p>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
            </p>
            {% else %}
            <p><i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
              <i class="rating__icon rating__icon--star fa fa-star"
                style="color:orange; cursor: pointer; font-size: 2rem;"></i>
            </p>
            {% endif %}

            <div class="d-flex justify-content-between align-items-center">
            <div>
            <h5 style="display:inline;">{{ comment.content }} </h5>- {{ comment.user}}
            </div>
            {% if request.user == comment.user %}
            <form action="{% url 'movies:movie_comment_delete' comment.pk movie.pk %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-danger" style="font-weight: 250px; font-size: 15px; margin-left: 5px; width:60px;">삭제</button>
            </form>
            {% endif %}
            </div>

          </div>
          <hr>
          {% endfor %}
        </div>
      </div>

      <div class="content-section mt-3">
        <div class="app-card">
          {% comment %} Review {% endcomment %}
          <h2> 리뷰 </h2>

          {% comment %} Review Create {% endcomment %}
          <h4 style="text-align: right;"> <a href="{% url 'movies:review_create' movie.pk %}"> 
          <button class="btn btn-warning" style="font-weight: 500px; font-size: 20px; margin-left: 5px; width:100px;"> 리뷰쓰기 </button></a></h4>

          {% comment %} Review List {% endcomment %}
          {% for review in reviews %}
          <div OnClick="location.href ='{% url 'movies:review' review.pk %}'" style="cursor:pointer;">
            <div class="app-card__subtext">
              <div class="d-flex justify-content-between align-items-center">
                <h3> <{{ review.title }}> </h5>
                {% if request.user == review.user %}
                <form action="{% url 'movies:review_delete' movie.pk review.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-danger" style="font-weight: 250px; font-size: 15px; margin-left: 5px; width:60px;">삭제</button>
                </form>
                {% endif %}
              </div>
              <h5>{{ review.content }}</h5>
              <p style="text-align: right;">{{ review.user }}</p>
              <div>
              {% if review.draw %}
              <img src="{{review.draw.url}}" alt="" style="height:250px; border-radius:10%; opacity: 0.8;">
              {% endif %}
              </div>
            </div>
          </div>
          <hr>
          {% endfor %}

        </div>
      </div>

    </div>
  </div>
</div>
{% endblock content %}

{% block option_modal %}
<!-- Frame Expansion Modal -->
<div class="modal" id="imageModal" tabindex="-1">
  <div class="modal-dialog" style="max-width: 60%; margin-top: 300px;">
    <div class="modal-content" class="modal-content" style="border-radius: 30px; background-color: rgba(255,255,192,0.1); backdrop-filter: blur(10px); box-shadow: 2px 7px 15px 8px rgba(0,0,0,0.3);">
      <div class="modal-frame-body">
        <img src="" alt="" id="frameImg" style="padding:16px;">
      </div>
    </div>
  </div>
</div>

<!-- Trailer Modal -->
<div class="modal" id="trailerModal" tabindex="-1">
  <div class="modal-dialog " style="max-width: 60%;">
    <div class="modal-content" class="modal-content" style="border-radius: 30px; background-color: rgba(255,255,192,0.1); backdrop-filter: blur(10px); box-shadow: 2px 7px 15px 8px rgba(0,0,0,0.3);">
      <div class="modal-trailer-body" style="width: 100%; height:700px; border-radius:20%;">
        <iframe src="https://www.youtube.com/embed/{{movie.trailer_url}}?autoplay=1&mute=1" frameborder="0" width="100%" height="100%" style="padding:16px;"></iframe>
      </div>
    </div>
  </div>
</div>
{% endblock option_modal %}

{% block option_js %}
  {% comment %} Frame Expansion Script {% endcomment %}
  <script>
    const color_url = document.querySelector('#color_url')
    const src = color_url.getAttribute('src')
    const imagemodal = document.querySelector('#imagemodal')
    const color_barcode = document.querySelector('#frameImg')
    color_url.addEventListener('click', function(event) {
      color_barcode.src = src
    })
  </script>
  
  {% comment %} Trailer Script {% endcomment %}
  <script>
    let trailerModal = document.querySelector('#trailerModal')
    let iframe = document.querySelector('iframe')
    window.addEventListener('click', function (){
      iframe.setAttribute("src",iframe.getAttribute("src"))
    })
  </script>
{% endblock option_js %}

movies/templates/movies/review_update.html
{% extends 'base.html' %}
{% load static %}

{% block back_URL %} "{% url 'movies:review' review.pk %}" {% endblock back_URL %}

{% block content %}
<div class="main-container">
  <div class="main-header">
  </div>
  <div class="content-wrapper">
    <form action="{% url 'movies:review_update' review.pk %}" method="POST">
      {% csrf_token %}
      <div class="content-section mt-3">
        <h3> 제목 </h3>
        <div class="app-card mt-3">
          <input style="background: none; border:none; color:white; font-size:25px;" type="text" name="title"  value="{{review.title}}">
        </div>
      </div>

      <div class="content-section mt-5">
        <h3> 내용 </h3>
        <div class="app-card mt-3">
          <input style="background: none; border:none; color:white; height: 250px; font-size: 20px;" type="text"
            name="content" value="{{review.content}}">
        </div>
      </div>

      <div class="content-section mt-3">
        <div class="app-card mt-5">
          <button style="background: none; border:none;">
            <h1 style="color:white;">수정하기</h1>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}