accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.choice),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    point = models.IntegerField(default=0)

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomAuthenticationFrom(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = '__all__'
        
class CustomUserCreationFrom(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import CustomUserCreationFrom
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index', 1)
    
    if request.method == "POST":
        form = CustomUserCreationFrom(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationFrom()
    context = {
        'form': form
    }
    return render(request,'accounts/signup.html', context)

@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index', 1)
    
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:choice')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request,'accounts/login.html', context)


@require_http_methods(['GET','POST'])
@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

accounts/templates/accounts/login.html
{% load static %}
{% load bootstrap5 %}

<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">

    <!-- Required Import -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'accounts/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
    
    <!-- Style Sheet -->
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">

    {% comment %} Google Fonts {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    {% comment %} Favicon {% endcomment %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
    <title> 인공지능을 활용한 색체 기반 영화 추천 </title>
  </head>

  <body style="font-family: 'Noto Sans KR', sans-serif;">
    <div class="d-lg-flex half">

      {% comment %} Backgroud Video {% endcomment %}
      <div class="bg order-1 order-md-2">
        <video class="h-100 w-100" src="{% static 'accounts/images/login.mp4'%}" autoplay muted loop></video>
      </div>

      {% comment %} Login input {% endcomment %}
      <div class="contents order-2 order-md-1">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7">
              <div class="mb-4">
                <h1><span class="pink">로</span>그<span class="cyan">인</span></h1>
                <p class="mb-4">당신의 <span class="pink">색</span>을 위한 영화를 <span class="cyan"> 추천</span>합니다.</p>
              </div>
              <form action="" method="POST">
              {% csrf_token %}
              {% bootstrap_form form %}
              <button class="btn btn-primary w-100 login">로그인</button>
              </form>
              <span class="d-block text-center my-4">&mdash; or &mdash;</span>
              <button class="btn btn-primary w-100 signup" onclick="location.href='{% url 'accounts:signup' %}' ">회원가입</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    {% comment %} Required Scripts {% endcomment %}
  </body>
</html>

accounts/templates/accounts/signup.html
{% load static %}
{% load bootstrap5 %}

<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    
    <!-- Required Import -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">    
    <link rel="stylesheet" href="{% static 'accounts/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">

    {% comment %} Google Fonts {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    {% comment %} Favicon {% endcomment %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
    <title> 인공지능을 활용한 색체 기반 영화 추천 </title>
  </head>
  
  <body style="font-family: 'Noto Sans KR', sans-serif;">
    <div class="d-lg-flex half">

      {% comment %} Backgroud Video {% endcomment %}
      <div class="bg order-1 order-md-2">
        <video class="h-100 w-100" src="{% static 'accounts/images/login.mp4'%}" autoplay muted loop></video>
      </div>

      {% comment %} Signup {% endcomment %}
      <div class="contents order-2 order-md-1">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7">
              <div class="mb-4">
                <h1><span class="pink">회</span>원<span class="cyan">가</span>입</h1>
                <p class="mb-4">당신의 <span class="pink">색</span>을 위한 영화를 <span class="cyan"> 추천</span>합니다.</p>
              </div>
              <form action="" method="POST">
              {% csrf_token %}
              {% bootstrap_form form %}
              <button class="btn btn-primary w-100 login">회원가입</button>
              </form>
              <span class="d-block text-center my-4">&mdash; or &mdash;</span>
              <button class="btn btn-primary w-100 signup" onclick="location.href='{% url 'accounts:login' %}' ">로그인</button>
            </div>
          </div>
        </div>
      </div>
    </div>
      
    <!-- Required Scripts -->
  </body>
</html>